package com.example.dailyroutineofflineapp;
import android.app.*;import android.os.*;import android.graphics.Color;import android.graphics.drawable.GradientDrawable;import android.content.*;import android.view.*;import android.widget.*;import java.text.*;import java.util.*;
public class MainActivity extends Activity{
 LinearLayout root,list; TextView title,date,logo,progress; EditText user,pass; Button login,custom,add,logout; android.content.SharedPreferences p; int theme=0; String[] names={"Light","Dark","Ocean","Nature","Sunset","Purple","Midnight","System Default"}; int[] bg={0xFFF7F7F7,0xFF171717,0xFFE8F6FF,0xFFEAF7EA,0xFFFFF0E6,0xFFF2EAFF,0xFF10182A,0xFFFAFAFA}; int[] fg={0xFF111111,0xFFFFFFFF,0xFF102A43,0xFF17351D,0xFF4A2110,0xFF29133D,0xFFFFFFFF,0xFF111111};
 public void onCreate(Bundle b){super.onCreate(b);p=getSharedPreferences("settings",0);showLogin();}
 int B(){int t=p.getInt("theme",0); if(t==7)return (getResources().getConfiguration().uiMode&32)!=0?0xFF171717:0xFFF7F7F7;return bg[t];} int F(){int t=p.getInt("theme",0);if(t==7)return (getResources().getConfiguration().uiMode&32)!=0?Color.WHITE:Color.BLACK;return fg[t];}
 GradientDrawable shape(int c,int r){GradientDrawable g=new GradientDrawable();g.setColor(c);g.setCornerRadius(r);return g;}
 void showLogin(){setContentView(com.example.dailyroutineofflineapp.R.layout.activity_main);root=findViewById(R.id.root);logo=findViewById(R.id.logo);title=findViewById(R.id.title);user=findViewById(R.id.user);pass=findViewById(R.id.pass);login=findViewById(R.id.login);apply(root);logo.setText(p.getString("logo","✓"));login.setOnClickListener(v->{if(user.getText().toString().equals("Md Moyen Khan Shakib")&&pass.getText().toString().equals("425264"))showDash();else Toast.makeText(this,"Wrong login",0).show();});}
 void apply(View v){if(v instanceof TextView){((TextView)v).setTextColor(F()); if(p.getBoolean("large",false))((TextView)v).setTextSize(20);} if(v instanceof Button)((Button)v).setBackground(shape(0xFF3F51B5, p.getBoolean("round",false)?60:16));v.setBackground(v instanceof Button?v.getBackground():shape(B(),0));if(v instanceof ViewGroup){for(int i=0;i<((ViewGroup)v).getChildCount();i++)apply(((ViewGroup)v).getChildAt(i));}}
 void showDash(){root=new LinearLayout(this);root.setOrientation(LinearLayout.VERTICAL);root.setPadding(20,20,20,20);setContentView(root); LinearLayout head=new LinearLayout(this);head.setGravity(Gravity.CENTER_VERTICAL);logo=new TextView(this);logo.setText(p.getString("logo","✓"));logo.setTextSize(35);head.addView(logo,new LinearLayout.LayoutParams(60,70));title=new TextView(this);title.setText("Daily Routine");title.setTextSize(25);title.setTypeface(null,1);head.addView(title,new LinearLayout.LayoutParams(0,70,1));root.addView(head);date=new TextView(this);date.setText(new SimpleDateFormat("EEEE • dd MMMM yyyy",Locale.ENGLISH).format(new Date()));date.setTextSize(17);root.addView(date);progress=new TextView(this);root.addView(progress);ScrollView sv=new ScrollView(this);list=new LinearLayout(this);list.setOrientation(LinearLayout.VERTICAL);sv.addView(list);root.addView(sv,new LinearLayout.LayoutParams(-1,0,1));add=new Button(this);add.setText("+ Add Routine");custom=new Button(this);custom.setText("Customize");logout=new Button(this);logout.setText("Logout");root.addView(add);root.addView(custom);root.addView(logout);add.setOnClickListener(v->addRoutine());custom.setOnClickListener(v->customize());logout.setOnClickListener(v->showLogin());load();apply(root);}
 void load(){list.removeAllViews();int n=p.getInt("n",0),done=0;for(int i=0;i<n;i++){CheckBox c=new CheckBox(this);c.setText(p.getString("r"+i,"Routine"));c.setTextSize(18);c.setChecked(p.getBoolean("d"+i,false));if(c.isChecked())done++;final int x=i;c.setOnCheckedChangeListener((b,z)->{p.edit().putBoolean("d"+x,z).apply();load();});c.setOnLongClickListener(v->{new AlertDialog.Builder(this).setTitle("Delete routine?").setMessage(c.getText()).setNegativeButton("Cancel",null).setPositiveButton("Delete",(d,w)->delete(x)).show();return true;});list.addView(c);if(p.getBoolean("card",true))c.setBackground(shape(B(),18));}progress.setText("Completed: "+done+" / "+n);}
 void addRoutine(){final EditText e=new EditText(this);e.setHint("Routine name");new AlertDialog.Builder(this).setTitle("Add Routine").setView(e).setNegativeButton("Cancel",null).setPositiveButton("Add",(d,w)->{String s=e.getText().toString().trim();if(!s.isEmpty()){int n=p.getInt("n",0);p.edit().putString("r"+n,s).putBoolean("d"+n,false).putInt("n",n+1).apply();load();}}).show();}
 void delete(int x){int n=p.getInt("n",0);android.content.SharedPreferences.Editor e=p.edit();for(int i=x;i<n-1;i++){e.putString("r"+i,p.getString("r"+(i+1),""));e.putBoolean("d"+i,p.getBoolean("d"+(i+1),false));}e.remove("r"+(n-1));e.remove("d"+(n-1));e.putInt("n",n-1).apply();load();}
 void customize(){LinearLayout l=new LinearLayout(this);l.setOrientation(LinearLayout.VERTICAL);l.setPadding(20,10,20,10);ScrollView s=new ScrollView(this);s.addView(l);RadioGroup rg=new RadioGroup(this);for(int i=0;i<8;i++){RadioButton r=new RadioButton(this);r.setText(names[i]);r.setId(100+i);r.setChecked(p.getInt("theme",0)==i);rg.addView(r);}l.addView(label("Theme"));l.addView(rg);l.addView(label("App Logo"));RadioGroup lg=new RadioGroup(this);String[] ls={"✓","★","♥","◎"};for(String q:ls){RadioButton r=new RadioButton(this);r.setText(q);r.setTextSize(25);r.setChecked(p.getString("logo","✓").equals(q));lg.addView(r);}l.addView(lg);l.addView(label("Design"));CheckBox card=new CheckBox(this);card.setText("Card Board");card.setChecked(p.getBoolean("card",true));l.addView(card);CheckBox large=new CheckBox(this);large.setText("Large Text");large.setChecked(p.getBoolean("large",false));l.addView(large);CheckBox round=new CheckBox(this);round.setText("Rounded Buttons");round.setChecked(p.getBoolean("round",false));l.addView(round);Button save=new Button(this);save.setText("SAVE");l.addView(save);Button reset=new Button(this);reset.setText("RESET");l.addView(reset);new AlertDialog.Builder(this).setTitle("Customize").setView(s).setNegativeButton("Back",null).create();AlertDialog a=new AlertDialog.Builder(this).setTitle("Customize").setView(s).setNegativeButton("Back",null).create();a.setOnShowListener(x->{save.setOnClickListener(v->{int id=rg.getCheckedRadioButtonId();p.edit().putInt("theme",id<100?0:id-100).putString("logo",((RadioButton)lg.findViewById(lg.getCheckedRadioButtonId())).getText().toString()).putBoolean("card",card.isChecked()).putBoolean("large",large.isChecked()).putBoolean("round",round.isChecked()).apply();a.dismiss();showDash();});reset.setOnClickListener(v->{p.edit().clear().apply();a.dismiss();showDash();});});a.show();}
 TextView label(String x){TextView t=new TextView(this);t.setText(x);t.setTextSize(19);t.setTypeface(null,1);t.setPadding(0,12,0,4);return t;}
}
